import glob from 'glob';
import alias from '@rollup/plugin-alias';
import { babel } from '@rollup/plugin-babel';
import commonjs from '@rollup/plugin-commonjs';
import json from '@rollup/plugin-json';
import multi from '@rollup/plugin-multi-entry';
import replace from '@rollup/plugin-replace';
import { nodeResolve } from '@rollup/plugin-node-resolve';

export default {
  input: ['tests/bootstrap.js', ...glob.sync('tests/**/*-test.js')],
  output: {
    file: 'build/tests.bundle.js',
    format: 'es',
    sourcemap: true,
  },
  treeshake: false, // Disabled for build performance
  plugins: [
    alias({
      entries: [
        {
          find: '../../build/settings.json',
          replacement: '../../tests/settings.json',
        },
      ],
    }),
    babel({
      babelHelpers: 'bundled',
      exclude: 'node_modules/**',
      extensions: ['.js', '.ts'],
      plugins: [
        [
          'mockable-imports',
          {
            excludeDirs: ['tests'],
          },
        ],
        [
          'babel-plugin-istanbul',
          {
            exclude: ['**/node_modules/**', 'tests/**'],

            // These two configuration options needed to match the values that
            // vitest sets internally, so that they pick the coverage
            // instrumentation generated by babel-plugin-istanbul instead of
            // trying to generate their own.
            // See https://github.com/vitest-dev/vitest/discussions/7841#discussioncomment-12855608
            coverageGlobalScope: 'globalThis',
            coverageVariable: '__VITEST_COVERAGE__',
          },
        ],
      ],
    }),
    replace({
      preventAssignment: true,
      EXTENSION_TESTS: 'true',
    }),
    nodeResolve({ extensions: ['.js', '.ts'] }),
    commonjs(),
    json(),
    multi(),
  ],
};
