#!/bin/sh

set -eu

CHROME_STAGE_EXT_ID=iahhmhdkmkifclacffbofcnmgkpalpoj

# Upload and publish stage extension
CHROME_STAGE_EXT_ARCHIVE=dist/*-chrome-stage.zip
if [ ! -f $CHROME_STAGE_EXT_ARCHIVE ]; then
  echo "Chrome stage extension has not been built."
  exit 1
fi

./node_modules/.bin/webstore upload \
  --source $CHROME_STAGE_EXT_ARCHIVE \
  --extension-id $CHROME_STAGE_EXT_ID \
  --client-id $CHROME_WEBSTORE_CLIENT_ID \
  --client-secret $CHROME_WEBSTORE_CLIENT_SECRET \
  --refresh-token $CHROME_WEBSTORE_REFRESH_TOKEN \
  --auto-publish

