#!/bin/sh

# This script creates a new release of the Hypothesis browser extension
# using the latest version of the client available on npm.

set -eu

LATEST_CLIENT_VERSION=$(npm view hypothesis version)

# Check that working tree is clean
if ! git diff --quiet HEAD ; then
  echo "There are uncommitted changes in the working tree or index."
  exit 1
fi

# Fetch commits from main repo and write commit ref to `.git/FETCH_HEAD`
git fetch --quiet https://github.com/hypothesis/browser-extension.git master

# Check that HEAD is the latest commit on the
# github.com/hypothesis/browser-extension repo.
remote_head=$(cat .git/FETCH_HEAD | cut -f1)
local_head=$(git rev-parse HEAD)
if [ $remote_head != $local_head ]; then
  echo "Current commit does not match head of hypothesis/browser-extension.git:master"
  exit 1
fi

# Update client to latest version on npm
npm install --save-dev hypothesis@$LATEST_CLIENT_VERSION
git add package.json package-lock.json
git commit -m "Update Hypothesis client to $LATEST_CLIENT_VERSION"

# Tag new browser extension release with the same version number as the client
npm version $LATEST_CLIENT_VERSION

echo "$LATEST_CLIENT_VERSION has been tagged."
echo "After a successful Travis build, test the stage extension and then go to"
echo "the Chrome Web Store developer dashboard to publish the prod extension."
