name: Release

concurrency:
  group: ${{ github.event.repository.name }}-deploy
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      ref:
        description: 'Git commit to release'
        required: false
        type: string
  workflow_dispatch:

jobs:
  continuous-integration:
    uses: ./.github/workflows/continuous-integration.yml
    name: continuous integration
    with:
      ref: ${{ inputs.ref }}

  upload-packages:
    needs: continuous-integration
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
    - name: Cache the node_modules dir
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
    - name: Install
      run: yarn install --immutable
    - name: Fetch packages
      uses: actions/download-artifact@v4
      with:
        name: packages
        path: dist/
    - name: Upload packages
      env:
        CHROME_WEBSTORE_CLIENT_ID: ${{ secrets.CHROME_WEBSTORE_CLIENT_ID }}
        CHROME_WEBSTORE_CLIENT_SECRET: ${{ secrets.CHROME_WEBSTORE_CLIENT_SECRET }}
        CHROME_WEBSTORE_REFRESH_TOKEN: ${{ secrets.CHROME_WEBSTORE_REFRESH_TOKEN }}
        FIREFOX_AMO_KEY: ${{ secrets.FIREFOX_AMO_KEY }}
        FIREFOX_AMO_SECRET: ${{ secrets.FIREFOX_AMO_SECRET }}
      run: tools/deploy
