name: Update client
on:
  workflow_dispatch:
jobs:
  update-client:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.update-client.outputs.ref }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Cache the node_modules dir
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
    - name: Install
      run: yarn install --immutable
    - name: Update client
      id: update-client
      run: |
        git config --global user.name "Hypothesis GitHub Actions"
        git config --global user.email "hypothesis@users.noreply.github.com"
        tools/update-client
        echo "ref=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
